// src/components/SWNCharacterGenerator.vue
<template>
  <section class="main scifi">
    <h2>Stars Without Number Character Generator</h2>

    <div class="input-group">
      <label for="seed">Random Seed</label>
      <input type="text" name="seed" v-model="seed" />
    </div>
    <button v-on:click="generateCharacter">Generate From Seed</button>
    <button v-on:click="newSeed">Random Seed (and Generate)</button>
    <button v-on:click="saveCharacter">Save</button>

    <h3>Character</h3>

    <p><strong>Background:</strong> {{ character.background.name }}</p>
    <p><strong>Class:</strong> {{ character.characterClass.name }}</p>
    <p><strong>Hit Points:</strong> {{ character.hitPoints }}</p>
    <p v-if="character.effort > 0"><strong>Effort:</strong> {{ character.effort }}</p>
    <p><strong>Base Attack Bonus:</strong> +{{ character.attackBonus }}</p>
    <p><strong>Armor Class:</strong> {{ character.armorClass }}</p>
    <p><strong>Credits:</strong> {{ character.credits }}</p>

    <h4>Saving Throws</h4>

    <p><strong>Evasion:</strong> {{ character.savingThrowEvasion }}</p>
    <p><strong>Mental:</strong> {{ character.savingThrowMental }}</p>
    <p><strong>Physical:</strong> {{ character.savingThrowPhysical }}</p>

    <h4>Focuses</h4>

    <div v-for="focus in character.focuses" :key="focus.name">
      <strong>{{ focus.name }}</strong>, Level {{ focus.currentLevel }}
    </div>

    <h4>Stats</h4>

    <div class="stats">
      <div v-for="stat in character.stats" :key="stat.abbreviation">
        <strong>{{ stat.abbreviation }}:</strong> <span>{{ stat.score }} ({{ stat.modifier }})</span>
      </div>
    </div>

    <h4>Skills</h4>

    <div class="skills">
      <div v-for="skill in character.skills" :key="skill.name">
        {{ skill.name }}-{{ skill.level }}
      </div>
    </div>

    <h4>Abilities</h4>

    <div class="abilities">
      <div v-for="ability in character.abilities" :key="ability">
        {{ ability }}
      </div>
    </div>

    <h4>Weapons</h4>

    <div v-for="weapon in character.rangedWeapons" :key="weapon.name">
      <strong>{{ weapon.name }}:</strong> <span>{{ weapon.damage }} damage, {{ character.rangedAttackBonus }} attack bonus</span>
    </div>

    <div v-for="weapon in character.meleeWeapons" :key="weapon.name">
      <strong>{{ weapon.name }}:</strong> <span>{{ weapon.damage }} damage, {{ character.meleeAttackBonus }} attack bonus</span>
    </div>

    <h4>Armor</h4>

    <div v-for="item in character.armor" :key="item.name">
      <strong>{{ item.name }}:</strong> <span>{{ item.AC }} AC</span>
    </div>

    <h4>Equipment</h4>

    <div v-for="item in character.equipment" :key="item">
      {{ item }}
    </div>
  </section>
</template>

<script>
import * as iarnd from "../modules/random.js";
import * as CharGen from "../modules/swn/character.js";

const random = require("random");
const seedrandom = require("seedrandom");

export default {
  name: "SWNCharacterGenerator",
  data: function () {
    return {
      character: {},
      seed: '',
    }
  },
  methods: {
    generateCharacter: function () {
      random.use(seedrandom(this.seed));
      this.character = CharGen.generate();
    },
    newSeed: function () {
      this.seed = iarnd.randomString(13);
      this.generateCharacter();
    },
    saveCharacter: function () {
      let character = CharGen.formatAsText(this.character);

      const blob = new Blob([character], { type: "text/plain" });
      const link = document.createElement("a");
      link.href = window.URL.createObjectURL(blob);
      link.download = "swn-character.txt";
      link.click();
      URL.revokeObjectURL(link.href);
    },
  },
  created: function () {
    this.newSeed();
  },
}
</script>

<style>
div.abilities > div {
  border-left: 1px solid #aaa;
  margin-bottom: 1rem;
  padding-left: 1rem;
}
</style>

// src/components/characters/SwnCharacterGenerator.svelte
<script lang="ts">
  import * as RNG from '@ironarachne/rng';
  import { characters as CharGen, downloadSwnCharacterPdf } from '$lib/swn';
  import type { SWNCharacter } from '$lib/swn';
  import {
    buildCharacterNameSource,
    isCustomCharacterNameSource,
    restoreLockedCharacterName,
    rollCharacterNameForSource,
  } from '$lib/characters';
  import { type Culture, loadSavedCultures } from '$lib/culture';
  import { onMount } from 'svelte';
  import GeneratorPage from '$components/layout/GeneratorPage.svelte';
  import SeedControls from '$components/common/SeedControls.svelte';
  import CharacterNameSection from '$components/characters/CharacterNameSection.svelte';
  import DownloadPdfButton from '$components/common/DownloadPdfButton.svelte';

  const rng = new RNG.RNG(Date.now().toString());
  let seed = $state(rng.randomString(13));
  let lockSeed = $state(false);
  $effect(() => {
    rng.setSeed(seed);
  });
  let character: SWNCharacter | null = $state(null);
  let downloadingPdf = $state(false);

  let savedCultures = $state<Culture[]>([]);
  let nameSourceKind = $state<'default' | 'preset' | 'saved_culture'>('default');
  let presetSetName = $state('human');
  let savedCultureName = $state('');
  let firstName = $state('');
  let lastName = $state('');
  let lockName = $state(false);
  let namingGender = $state<'male' | 'female' | 'random'>('random');

  function applyNamesToCharacter(target: CharGen.SWNCharacter) {
    target.firstName = firstName;
    target.lastName = lastName;
  }

  function rollNamesForCurrentSource() {
    const source = buildCharacterNameSource(
      nameSourceKind,
      presetSetName,
      savedCultureName,
      savedCultures,
    );
    const nameRng = new RNG.RNG(`${Date.now()}-swn-name`);
    return rollCharacterNameForSource(nameRng, source, 'human', namingGender);
  }

  function applyGeneratedNamesFromSource(target: CharGen.SWNCharacter) {
    const source = buildCharacterNameSource(
      nameSourceKind,
      presetSetName,
      savedCultureName,
      savedCultures,
    );
    if (!isCustomCharacterNameSource(source)) {
      target.firstName = '';
      target.lastName = '';
      firstName = '';
      lastName = '';
      return;
    }

    const generated = rollNamesForCurrentSource();
    target.firstName = generated.firstName;
    target.lastName = generated.lastName;
    firstName = generated.firstName;
    lastName = generated.lastName;
  }

  function generate() {
    if (!lockSeed) {
      seed = rng.randomString(13);
    }
    rng.setSeed(seed);

    const lockedFirstName = firstName;
    const lockedLastName = lastName;

    character = CharGen.generate(rng);
    if (lockName) {
      restoreLockedCharacterName(character, lockedFirstName, lockedLastName);
    } else {
      applyGeneratedNamesFromSource(character);
    }
  }

  function generateNameOnly() {
    if (lockName) {
      return;
    }
    const generated = rollNamesForCurrentSource();
    firstName = generated.firstName;
    lastName = generated.lastName;
    if (character) {
      character.firstName = generated.firstName;
      character.lastName = generated.lastName;
    }
  }

  function save() {
    if (!character) return;
    applyNamesToCharacter(character);
    const saveData = CharGen.formatAsText(character);

    const blob = new Blob([saveData], { type: 'text/plain' });
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.download = 'swn-character.txt';
    link.click();
    URL.revokeObjectURL(link.href);
  }

  async function downloadPdf() {
    if (downloadingPdf || !character) {
      return;
    }

    applyNamesToCharacter(character);
    downloadingPdf = true;
    try {
      await downloadSwnCharacterPdf(character);
    } finally {
      downloadingPdf = false;
    }
  }

  onMount(() => {
    savedCultures = loadSavedCultures();
    if (savedCultures.length > 0) {
      savedCultureName = savedCultures[0]!.name;
    }
    generate();
  });
</script>

<GeneratorPage theme="scifi" title="Stars Without Number Character Generator">
  <SeedControls bind:seed bind:lockSeed />

  <CharacterNameSection
    bind:nameSourceKind
    bind:presetSetName
    bind:savedCultureName
    bind:firstName
    bind:lastName
    bind:lockName
    bind:namingGender
    showGenderPicker={true}
    seed="swn-name-sets"
    onGenerateName={generateNameOnly}
  />

  <button onclick={generate}>Generate</button>
  <button onclick={save}>Save</button>
  <DownloadPdfButton onclick={downloadPdf} downloading={downloadingPdf} />

  <h2>{firstName || lastName ? `${firstName} ${lastName}`.trim() : 'Character'}</h2>

  {#if character}
    <p><strong>Background:</strong> {character.background.name}</p>
    <p><strong>Class:</strong> {character.characterClass.name}</p>
    <p><strong>Hit Points:</strong> {character.hitPoints}</p>
    {#if character.effort > 0}
      <p><strong>Effort:</strong> {character.effort}</p>
    {/if}
    <p><strong>Base Attack Bonus:</strong> +{character.attackBonus}</p>
    <p><strong>Armor Class:</strong> {character.armorClassEquipped}</p>
    <p><strong>Credits:</strong> {character.credits}</p>

    <h3>Saving Throws</h3>

    <p><strong>Evasion:</strong> {character.savingThrowEvasion}</p>
    <p><strong>Mental:</strong> {character.savingThrowMental}</p>
    <p><strong>Physical:</strong> {character.savingThrowPhysical}</p>

    <h3>Focuses</h3>

    {#each character.focuses as focus}
      <div>
        <strong>{focus.name}</strong>, Level {focus.currentLevel}
      </div>
    {/each}

    <h3>Stats</h3>

    <div class="stats">
      {#each character.stats as stat}
        <div>
          <strong>{stat.abbreviation}:</strong>
          <span>{stat.score} ({stat.modifier})</span>
        </div>
      {/each}
    </div>

    <h3>Skills</h3>

    <div class="skills">
      {#each character.skills as skill}
        <div>
          {skill.name}-{skill.level}
        </div>
      {/each}
    </div>

    <h3>Abilities</h3>

    <div class="abilities">
      {#each character.abilities as ability}
        <div>
          {ability.description}
        </div>
      {/each}
    </div>

    <h3>Weapons</h3>

    <div class="weapons">
      {#each character.rangedWeapons as weapon}
        <div>
          {weapon.name}: {weapon.damage}, ATK +{character.rangedAttackBonus} (rng)
        </div>
      {/each}
      {#each character.meleeWeapons as weapon}
        <div>
          {weapon.name}: {weapon.damage}, ATK +{character.meleeAttackBonus} (mel)
        </div>
      {/each}
    </div>

    <h3>Armor</h3>

    <div class="armor">
      {#each character.armor as item}
        <div>{item.name}: AC {item.ac}</div>
      {/each}
    </div>

    <h3>Equipment</h3>

    <div class="equipment">
      {#each character.equipment as item}
        <div>{item.name}</div>
      {/each}
    </div>
  {/if}
</GeneratorPage>

<style>
  .stats,
  .skills,
  .abilities,
  .weapons,
  .armor,
  .equipment {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 0.5rem;
  }
</style>
