// src/components/ChopShopGenerator.vue
<template>
  <section class="cyberpunk main">
    <h2>Chop Shop Generator</h2>
    <p>This is a cyberpunk chop shop generator.</p>
    <button v-on:click="generateChopShop">Generate</button>
    <p>{{ description }}</p>
  </section>
</template>

<script>
import * as ChopShop from "../modules/chopshop";

const random = require("random");
const seedrandom = require("seedrandom");

export default {
  name: "ChopShopGenerator",
  data: function () {
    return {
      description: "",
    };
  },
  methods: {
    generateChopShop: function () {
      random.use(seedrandom(this.seed));
      this.description = ChopShop.generate();
    },
  },
  created: function () {
    this.generateChopShop();
  },
};
</script>

// src/components/locations/ChopShopGenerator.svelte
<script lang="ts">
  import * as ChopShop from '$lib/chopshop';
  import { RNG } from '@ironarachne/rng';
  import GeneratorPage from '$components/layout/GeneratorPage.svelte';

  let shopDescription = $state('');
  let seed = new RNG(Date.now().toString()).randomString(13);

  function generateChopShop() {
    seed = new RNG(Date.now().toString()).randomString(13);
    const rng = new RNG(seed);
    shopDescription = ChopShop.generate(rng);
  }

  generateChopShop();
</script>

<GeneratorPage theme="cyberpunk" title="Chop Shop Generator">
  {#snippet description()}
    <p>This is a cyberpunk chop shop generator.</p>
  {/snippet}

  <button onclick={generateChopShop}>Generate</button>

  <p>{shopDescription}</p>
</GeneratorPage>
