// src/components/Footer.vue
<template>
	<footer>
		<p>Copyright &copy; 2020 Ben Overmyer. All rights reserved.</p>
	</footer>
</template>

<script>
	export default {
		name: 'Footer',
		props: {}
	}
</script>

<style scoped lang="scss">
	$ironarachnegreen: #76E841;
	$tan: #5C5031;
	$gold: #FAD037;
	
	footer {
		font-size: 0.75rem;
		margin-top: 1rem;
	}
</style>

// src/lib/components/Footer.svelte
<script lang="ts">
let date = new Date();
let year = date.getFullYear();
</script>

<style lang="scss">
footer {
  font-size: 0.75rem;
  margin-top: 1rem;
}
</style>

<footer>
  <p>Copyright &copy; {year} Ben Overmyer. All rights reserved.</p>
  <p>The source code for this site is available on <a href="https://github.com/ironarachne/ironarachne">GitHub</a>.</p>
  <p>Follow me on <a rel="me" href="https://fosstodon.org/@dungeonHack">Mastodon</a>.</p>
</footer>
